---
apiVersion: v2
name: shadowbroker
version: 0.9.81
appVersion: "0.9.81"
description: simple shadowbroker installation
type: application

dependencies:
  - name: app-template
    alias: shadowbroker
    version: ~4
    repository: https://bjw-s-labs.github.io/helm-charts/
