export const airlineNames: Record<string, string> = {
  'N/A': 'Unknown',
  RNX: '1Time Airline',
  MLA: '40-Mile Air',
  AAA: 'Ansett Australia',
  AAF: 'Aigle Azur',
  AAH: 'Aloha Airlines',
  AAL: 'American Airlines',
  AAR: 'Asiana Airlines',
  AAS: 'Askari Aviation',
  AAW: 'Afriqiyah Airways',
  AAY: 'Allegiant Air',
  TUS: 'ABSA - Aerolinhas Brasileiras',
  ACP: 'Astral Aviation',
  ADE: 'Ada Air',
  ADR: 'Adria Airways',
  AEA: 'Air Europa',
  AEB: 'Aero Benin',
  AEE: 'Aegean Airlines',
  AEL: 'Air Europe',
  AER: 'Alaska Central Express',
  AES: 'ACES Colombia',
  AEU: 'Astraeus',
  AEW: 'Aerosvit Airlines',
  AEY: 'Air Italy',
  UTY: 'Alliance Airlines',
  AFG: 'Ariana Afghan Airlines',
  AFL: 'Aeroflot Russian Airlines',
  BON: 'Air Bosna',
  AFR: 'Air France',
  ACI: 'Air Caledonie International',
  SNC: 'Air Cargo Carriers',
  NMB: 'Air Namibia',
  SLI: 'Aerolitoral',
  AGV: 'Air Glaciers',
  AGX: 'Aviogenex',
  PLI: 'Aeroper',
  BMM: 'Atlas Blue',
  AHY: 'Azerbaijan Airlines',
  AIA: 'Avies',
  ABQ: 'Airblue',
  AIR: 'Airlift International',
  BER: 'Air Berlin',
  AIC: 'Air India Limited',
  BUB: 'Air Bourbon',
  ABD: 'Air Atlanta Icelandic',
  THT: 'Air Tahiti Nui',
  AIZ: 'Arkia Israel Airlines',
  AJM: 'Air Jamaica',
  ADH: 'Air One',
  RSH: 'Air Sahara',
  AMC: 'Air Malta',
  AJX: 'Air Japan',
  AKA: 'Air Korea Co. Ltd.',
  AKL: 'Air Kiribati',
  AWE: 'America West Airlines',
  AWI: 'Air Wisconsin',
  TAK: 'Tatarstan Airlines',
  ALO: 'Allegheny Commuter Airlines',
  RSI: 'Air Sunshine',
  AML: 'Air Malawi',
  AMT: 'ATA Airlines',
  AMU: 'Air Macau',
  AMV: 'AMC Airlines',
  SEY: 'Air Seychelles',
  AMX: 'AeroM\u00e9xico',
  ANA: 'All Nippon Airways',
  ANE: 'Air Nostrum',
  ANG: 'Air Niugini',
  ABY: 'Air Arabia',
  ACA: 'Air Canada',
  BTI: 'Air Baltic',
  ANK: 'Air Nippon',
  ANO: 'Airnorth',
  ANT: 'Air North Charter - Canada',
  ANZ: 'Air New Zealand',
  SMX: 'Alitalia Express',
  ARF: 'Aero Flight',
  APW: 'Arrow Air',
  ARD: 'Aerocondor',
  ARE: 'Aires',
  ARG: 'Aerolineas Argentinas',
  ASA: 'Alaska Airlines',
  ASD: 'Air Sinai',
  ASQ: 'Atlantic Southeast Airlines',
  ASZ: 'Astrakhan Airlines',
  ATC: 'Air Tanzania',
  VBW: 'Air Burkina',
  ATM: 'Airlines Of Tasmania',
  SPM: 'Air Saint Pierre',
  AUA: 'Austrian Airlines',
  WOW: 'Air Southwest',
  AUB: 'Augsburg Airways',
  TUR: 'ATUR',
  AUH: 'Abu Dhabi Amiri Flight',
  AUL: 'Aeroflot-Nord',
  AUR: 'Aurigny Air Services',
  AUT: 'Austral Lineas Aereas',
  AVA: 'Avianca - Aerovias Nacionales de Colombia',
  AVN: 'Air Vanuatu',
  BGD: 'Air Bangladesh',
  BIE: 'Air Mediterranee',
  TAH: 'Air Moorea',
  AWU: 'Aeroline GmbH',
  AWW: 'Air Wales',
  FWI: 'Air Cara\u00efbes',
  AXB: 'Air India Express',
  AXL: 'Air Exel',
  AXM: 'AirAsia',
  AYZ: 'Atlant-Soyuz Airlines',
  AZA: 'Alitalia',
  AZN: 'Amaszonas',
  AZW: 'Air Zimbabwe',
  OCA: 'Aserca Airlines',
  SDM: 'Rossiya-Russian Airlines',
  EGF: 'American Eagle Airlines',
  VUE: 'AD Aviation',
  VUN: 'Air Ivoire',
  BOT: 'Air Botswana',
  UPA: 'Air Foyle',
  VTA: 'Air Tahiti',
  VIM: 'Air VIA',
  WTA: 'Africa West',
  VAS: 'ATRAN Cargo Airlines',
  CCA: 'Air China',
  CDP: 'Aero Condor Peru',
  CVA: 'Air Chathams',
  CWM: 'Air Marshall Islands',
  CYD: 'Access Air',
  DAH: 'Air Algerie',
  DHI: 'Adam Air',
  DLA: 'Air Dolomiti',
  DNV: 'Aeroflot-Don',
  DRD: 'Air Madrid',
  EIN: 'Aer Lingus',
  FIF: 'Air Finland',
  FIX: 'Airfix Aviation',
  FJI: 'Air Pacific',
  FLI: 'Atlantic Airways',
  FLZ: 'Air Florida',
  FXI: 'Air Iceland',
  GAP: 'Air Philippines',
  GIP: 'Air Guinee Express',
  GRL: 'Air Greenland',
  GTI: 'Atlas Air',
  GUY: 'Air Guyane',
  JAB: 'Air Bagan',
  JZA: 'Air Canada Jazz',
  KKK: 'Atlasjet',
  KOR: 'Air Koryo',
  KZR: 'Air Astana',
  LBC: 'Albanian Airlines',
  LFA: 'Air Alfa',
  LNE: 'Aerolane',
  LUR: 'Atlantis European Airways',
  LXR: 'Air Luxor',
  MAU: 'Air Mauritius',
  MDG: 'Air Madagascar',
  MLD: 'Air Moldova',
  MMD: 'Alsie Express',
  MPD: 'Air Plus Comet',
  NIG: 'Aero Contractors',
  PEL: 'Aeropelican Air Services',
  REA: 'Aer Arann',
  REU: 'Air Austral',
  RIT: 'Asian Spirit',
  RKA: 'Air Afrique',
  RLA: 'Airlinair',
  RLN: 'Aero Lanka',
  RNE: 'Air Salone',
  RNV: 'Armavia',
  RPB: 'AeroRep',
  RSR: 'Aero-Service',
  RSU: 'Aerosur',
  RTE: 'Aeronorte',
  SMJ: 'Avient Aviation',
  SYL: 'Aircompany Yakutia',
  TAO: 'Aeromar',
  TFL: 'Arkefly',
  TOK: 'Airlines PNG',
  TRS: 'AirTran Airways',
  TSC: 'Air Transat',
  TWN: 'Avialeasing Aviation Company',
  TYR: 'Tyrolean Airways',
  GLG: 'Aerolineas Galapagos (Aerogal)',
  DRU: 'Alrosa Mirny Air Enterprise',
  BAW: 'British Airways',
  BBC: 'Biman Bangladesh Airlines',
  BHP: 'Belair Airlines',
  BHS: 'Bahamasair',
  BIH: 'British International Helicopters',
  BKF: 'BF-Lento OY',
  BKP: 'Bangkok Airways',
  BLF: 'Blue1',
  BLL: 'Baltic Airlines',
  BLS: 'Bearskin Lake Air Service',
  BLV: 'Bellview Airlines',
  BMA: 'bmi',
  BMI: 'bmibaby',
  BMJ: 'Bemidji Airlines',
  BMR: 'British Midland Regional',
  BPA: 'Blue Panorama Airlines',
  BPS: 'Budapest Aircraft Services/Manx2',
  BRG: 'Bering Air',
  BRS: 'Brazilian Air Force',
  BRU: 'Belavia Belarusian Airlines',
  BTV: 'Metro Batavia',
  BVT: 'Berjaya Air',
  BWG: 'Blue Wings',
  BZH: 'Brit Air',
  DAT: 'Brussels Airlines',
  IBB: 'Binter Canarias',
  JOR: 'Blue Air',
  LAJ: 'British Mediterranean Airways',
  LZB: 'Bulgaria Air',
  NKF: 'Barents AirLink',
  ICL: 'CAL Cargo Air Lines',
  CLI: 'Calima Aviacion',
  CDN: 'Canadian Airlines',
  MPE: 'Canadian North',
  KAP: 'Cape Air',
  BWA: 'Caribbean Airlines',
  KRP: 'Carpatair',
  CPN: 'Caspian Airlines',
  CPA: 'Cathay Pacific',
  CAY: 'Cayman Airways',
  CEB: 'Cebu Pacific',
  CCG: 'Central Connect Airlines',
  CLW: 'Centralwings',
  CHW: 'Charter Air',
  CHQ: 'Chautauqua Airlines',
  CAL: 'China Airlines',
  CES: 'China Eastern Airlines',
  CSN: 'China Southern Airlines',
  CUA: 'China United Airlines',
  CYH: 'Yunnan Airlines',
  CIM: 'Cimber Air',
  RUS: 'Cirrus Airlines',
  SDR: 'City Airline',
  CIX: 'City Connexion Airlines',
  BCY: 'CityJet',
  CFE: 'BA CityFlyer',
  CGK: 'Click Airways',
  CJC: 'Colgan Air',
  COM: 'Comair',
  CAW: 'Comair',
  UCA: 'CommutAir',
  CWK: 'Comores Airlines',
  CPZ: 'Compass Airlines',
  CFG: 'Condor Flugdienst',
  CHP: 'Consorcio Aviaxsa',
  KIS: 'Contact Air',
  COA: 'Continental Airlines',
  CMI: 'Continental Micronesia',
  VCV: 'Conviasa',
  CMP: 'Copa Airlines',
  AAQ: 'Copterline',
  CAI: 'Corendon Airlines',
  CRL: 'Corsairfly',
  CCM: 'Corse-Mediterranee',
  CAN: 'Crest Aviation',
  CTN: 'Croatia Airlines',
  CRO: 'Crown Airways',
  CUB: 'Cubana de Aviaci\u00f3n',
  CYP: 'Cyprus Airways',
  CSA: 'Czech Airlines',
  DTR: 'DAT Danish Air Transport',
  DAO: 'Daallo Airlines',
  KHB: 'Dalavia',
  DWT: 'Darwin Airline',
  DEA: 'Delta Aerotaxi',
  DAL: 'Delta Air Lines',
  DNM: 'Denim Air',
  DJB: 'Djibouti Airlines',
  UDN: 'Dniproavia',
  DOA: 'Dominicana de Aviaci',
  DMO: 'Domodedovo Airlines',
  UDC: 'DonbassAero',
  HDA: 'Dragonair',
  DRK: 'Druk Air',
  DBK: 'Dubrovnik Air',
  DNL: 'Dutch Antilles Express',
  BAG: 'dba',
  EVA: 'EVA Air',
  UGX: 'East African',
  EZE: 'Eastern Airways',
  ELA: 'Eastland Air',
  ECU: 'Ecuavia',
  EDW: 'Edelweiss Air',
  MSR: 'Egyptair',
  ELY: 'El Al Israel Airlines',
  BRQ: 'El-Buraq Air Transport',
  UAE: 'Emirates',
  EEA: 'Empresa Ecuatoriana De Aviacion',
  ERT: 'Eritrean Airlines',
  ELL: 'Estonian Air',
  ETH: 'Ethiopian Airlines',
  ETD: 'Etihad Airways',
  ECA: 'Eurocypria Airlines',
  EEU: 'Eurofly Service',
  ELO: 'Eurolot',
  EAL: 'European Air Express',
  EWG: 'Eurowings',
  EIA: 'Evergreen International Airlines',
  XLA: 'Excel Airways',
  XEL: 'Excel Charter',
  LHN: 'Express One International',
  BTA: 'ExpressJet',
  EZY: 'easyJet',
  EFA: 'Far Eastern Air Transport',
  FIN: 'Finnair',
  WBA: 'Finncomm Airlines',
  FFM: 'Firefly',
  FAB: 'First Air',
  FCA: 'First Choice Airways',
  FLT: 'Flightline',
  FWL: 'Florida West International Airways',
  XAX: 'AirAsia X',
  LIL: 'FlyLal',
  NDC: 'FlyNordic',
  BBO: 'Flybaboo',
  BEE: 'Flybe',
  GSM: 'Flyglobespan',
  FYH: 'Flyhy Cargo Airlines',
  FOS: 'Formosa Airlines',
  FRE: 'Freedom Air',
  FRL: 'Freedom Airlines',
  FFT: 'Frontier Airlines',
  FTA: 'Frontier Flying Service',
  GBL: 'GB Airways',
  GIA: 'Garuda Indonesia',
  GZP: 'Gazpromavia',
  TGZ: 'Georgian Airways',
  GFG: 'Georgian National Airlines',
  GMI: 'Germania',
  GWI: 'Germanwings',
  GHB: 'Ghana International Airlines',
  GOW: 'Go Air',
  GJS: 'GoJet Airlines',
  GLO: 'Gol Transportes A\u00e9reos',
  GAO: 'Golden Air',
  GLA: 'Great Lakes Airlines',
  TAT: 'Grupo TACA',
  GFA: 'Gulf Air',
  GBA: 'Gulf Air Bahrain',
  GFT: 'Gulfstream International Airlines',
  HAG: 'Hageland Aviation Services',
  CHH: 'Hainan Airlines',
  HAM: 'Haiti Ambassador Airlines',
  HHI: 'Hamburg International',
  HLX: 'TUIfly',
  HLF: 'Hapagfly',
  HAL: 'Hawaiian Airlines',
  HFR: 'Heli France',
  JBA: 'Helijet',
  HEJ: 'Hellas Jet',
  FHE: 'Hello',
  OAW: 'Helvetic Airways',
  HER: "Hex'Air",
  HWY: 'Highland Airways',
  ADO: 'Hokkaido International Airlines',
  CRK: 'Hong Kong Airlines',
  HKE: 'Hong Kong Express Airways',
  QXE: 'Horizon Air',
  HZA: 'Horizon Airlines',
  IBE: 'Iberia Airlines',
  IWD: 'Iberworld',
  IBX: 'Ibex Airlines',
  RAC: 'Royal Air Cambodge',
  ICE: 'Icelandair',
  ITX: 'Imair Airlines',
  IGO: 'IndiGo Airlines',
  IAC: 'Indian Airlines',
  IBU: 'Indigo',
  AWQ: 'Indonesia AirAsia',
  IAA: 'Indonesian Airlines',
  ILN: 'Interair South Africa',
  SUW: 'Interavia Airlines',
  ITK: 'Interlink Airlines',
  ISK: 'Intersky',
  IRA: 'Iran Air',
  IRC: 'Iran Aseman Airlines',
  IAW: 'Iraqi Airways',
  CGP: 'Cargo Plus Aviation',
  ISW: 'Islas Airways',
  ISV: 'Islena De Inversiones',
  ISR: 'Israir',
  IKA: 'Itek Air',
  JEX: 'JAL Express',
  JAZ: 'JALways',
  JAL: 'Japan Airlines',
  JAA: 'Japan Asia Airways',
  JTA: 'Japan Transocean Air',
  JAT: 'Jat Airways',
  JZR: 'Jazeera Airways',
  JJA: 'Jeju Air',
  JAI: 'Jet Airways',
  JSA: 'Jetstar Asia Airways',
  EXS: 'Jet2.com',
  JFU: 'Jet4You',
  JBU: 'JetBlue Airways',
  JAF: 'Jetairfly',
  JEF: 'Jetflite',
  JST: 'Jetstar Airways',
  DKH: 'Juneyao Airlines',
  KNI: 'KD Avia',
  KLC: 'KLM Cityhopper',
  KLM: 'KLM Royal Dutch Airlines',
  KMF: 'Kam Air',
  MVD: 'Kavminvodyavia',
  KDA: 'Kendell Airlines',
  KEN: 'Kenmore Air',
  KQA: 'Kenya Airways',
  KFR: 'Kingfisher Airlines',
  IRK: 'Kish Air',
  KGL: 'Kogalymavia Air Company',
  KAL: 'Korean Air',
  KSM: 'Kosmos',
  KJC: 'Krasnojarsky Airlines',
  KIL: 'Kuban Airlines',
  KAC: 'Kuwait Airways',
  KZU: 'Kuzu Airlines Cargo',
  LRC: 'LACSA',
  LAN: 'LAN Airlines',
  DSM: 'LAN Argentina',
  LXP: 'LAN Express',
  LPE: 'LAN Peru',
  LOT: 'LOT Polish Airlines',
  LTE: 'LTE International Airways',
  LTO: 'LTU Austria',
  LTU: 'LTU International',
  LAO: 'Lao Airlines',
  LTC: 'LatCharter',
  LDA: 'Lauda Air',
  LIA: 'Leeward Islands Air Transport',
  LAA: 'Libyan Arab Airlines',
  LAM: 'Linhas A',
  LNI: 'Lion Mentari Airlines',
  LGW: 'Luftfahrtgesellschaft Walter',
  DLH: 'Lufthansa',
  GEC: 'Lufthansa Cargo',
  CLH: 'Lufthansa CityLine',
  LTR: 'Lufttransport',
  LGL: 'Luxair',
  LPR: 'L',
  MAA: 'MasAir',
  MAK: 'MAT Macedonian Airlines',
  MGL: 'MIAT Mongolian Airlines',
  MNB: 'MNG Airlines',
  MCK: 'Macair Airlines',
  IRM: 'Mahan Air',
  MAS: 'Malaysia Airlines',
  MAC: 'Malta Air Charter',
  MAH: 'Mal\u00e9v',
  MDL: 'Mandala Airlines',
  MDA: 'Mandarin Airlines',
  MNO: 'Mango',
  MPH: 'Martinair',
  MXL: 'Maxair',
  MYD: 'Maya Island Air',
  ISS: 'Meridiana',
  MNA: 'Merpati Nusantara Airlines',
  ASH: 'Mesa Airlines',
  MES: 'Mesaba Airlines',
  MXA: 'Mexicana de Aviaci',
  MEA: 'Middle East Airlines',
  MDW: 'Midway Airlines',
  MEP: 'Midwest Airlines',
  MWA: 'Midwest Airlines (Egypt)',
  MDV: 'Moldavian Airlines',
  MON: 'Monarch Airlines',
  MGX: 'Montenegro Airlines',
  MAL: 'Morningstar Air Express',
  GAI: 'Moskovia Airlines',
  MSI: 'Motor Sich',
  MYT: 'MyTravel Airways',
  UBA: 'Myanma Airways',
  MMM: 'Myanmar Airways International',
  MYA: 'Myflug',
  NAS: 'Nasair',
  NJS: 'National Jet Systems',
  NTW: 'Nationwide Airlines',
  RON: 'Nauru Air Corporation',
  RNA: 'Nepal Airlines',
  EJA: 'NetJets',
  NEA: 'New England Airlines',
  NTJ: 'NextJet',
  NLY: 'Niki',
  NOK: 'Nok Air',
  NCF: 'Norfolk County Flight College',
  NTM: 'North American Airlines',
  HMR: 'North American Charters',
  NWA: 'Northwest Airlines',
  PLR: 'Northwestern Air',
  NAX: 'Norwegian Air Shuttle',
  TFN: 'Norwegian Aviation College',
  LBT: 'Nouvel Air Tunisie',
  NVR: 'Novair',
  KNE: 'Nas Air',
  OHK: 'Oasis Hong Kong Airlines',
  BCN: 'Ocean Air',
  ONE: 'Oceanair',
  OAL: 'Olympic Airlines',
  OMA: 'Oman Air',
  OAE: 'Omni Air International',
  OTG: 'One Two Go Airlines',
  OHY: 'Onur Air',
  ORB: 'Orenburg Airlines',
  OEA: 'Orient Thai Airlines',
  OGN: 'Origin Pacific Airways',
  OLT: 'Ostfriesische Lufttransport',
  OLA: 'Overland Airways',
  OZJ: 'Ozjet Airlines',
  PNR: 'PAN Air',
  PBA: 'PB Air',
  PUA: 'PLUNA',
  PMT: 'PMTair',
  PIC: 'Jetstar Pacific',
  PCO: 'Pacific Coastal Airline',
  PEC: 'Pacific East Asia Cargo Airlines',
  PSA: 'Pacific Island Aviation',
  NMI: 'Pacific Wings',
  PIA: 'Pakistan International Airlines',
  PMW: 'Paramount Airways',
  PTB: 'Passaredo Transportes Aereos',
  PGT: 'Pegasus Airlines',
  PEN: 'Peninsula Airways',
  PAL: 'Philippine Airlines',
  PDT: 'Piedmont Airlines (1948-1989)',
  FLG: 'Pinnacle Airlines',
  POT: 'Polet',
  PAO: 'Polynesian Airlines',
  POE: 'Porter Airlines',
  PGA: 'Portugalia',
  PDC: 'Potomac Air',
  PRF: 'Precision Air',
  PTI: 'Privatair',
  QFA: 'Qantas',
  QTR: 'Qatar Airways',
  KIN: 'Kinloss Flying Training Unit',
  RXA: 'Regional Express',
  RPA: 'Republic Airlines',
  RPH: 'Republic Express Airlines',
  RAR: 'Air Rarotonga',
  RAM: 'Royal Air Maroc',
  RBA: 'Royal Brunei Airlines',
  RJA: 'Royal Jordanian',
  PPW: 'Royal Phnom Penh Airways',
  RLU: 'Rusline',
  RWD: 'Rwandair Express',
  RYA: 'Ryan Air Services',
  RYN: 'Ryan International Airlines',
  RYR: 'Ryanair',
  RAE: 'R\u00e9gional',
  RZO: 'SATA International',
  SAA: 'South African Airways',
  SAI: 'Shaheen Air International',
  SAS: 'Scandinavian Airlines System',
  SAY: 'ScotAirways',
  SBI: 'S7 Airlines',
  SBS: 'Seaborne Airlines',
  SCE: 'Scenic Airlines',
  ALK: 'SriLankan Airlines',
  SCX: 'Sun Country Airlines',
  SEA: 'Southeast Air',
  SEH: 'Sky Express',
  SEJ: 'Spicejet',
  SFJ: 'Star Flyer',
  SGY: 'Skagway Air Service',
  SHD: 'Sahara Airlines',
  SAT: 'SATA Air Acores',
  SIA: 'Singapore Airlines',
  SIB: 'Sibaviatrans',
  SIH: 'Skynet Airlines',
  SJY: 'Sriwijaya Air',
  SMY: 'Sama Airlines',
  SQC: 'Singapore Airlines Cargo',
  SRH: 'Siem Reap Airways',
  SRQ: 'South East Asian Airlines',
  SSV: 'Skyservice Airlines',
  STU: 'Servicios de Transportes A',
  SUD: 'Sudan Airways',
  SVA: 'Saudi Arabian Airlines',
  SWA: 'Southwest Airlines',
  SWD: 'Southern Winds Airlines',
  SWR: 'Swiss International Air Lines',
  SWU: 'Swiss European Air Lines',
  SWV: 'Swe Fly',
  SXS: 'SunExpress',
  SYR: 'Syrian Arab Airlines',
  SYX: 'Skywalk Airlines',
  CDG: 'Shandong Airlines',
  CNO: 'SAS Braathens',
  CQH: 'Spring Airlines',
  CSC: 'Sichuan Airlines',
  CSH: 'Shanghai Airlines',
  CSZ: 'Shenzhen Airlines',
  ERO: "Sun D'Or",
  ESK: 'SkyEurope',
  HSK: 'Sky Europe Airlines',
  JKK: 'Spanair',
  NKS: 'Spirit Airlines',
  NSE: 'SATENA',
  OZW: 'Skywest Airlines',
  BBR: 'Santa Barbara Airlines',
  SKU: 'Sky Airline',
  SKW: 'SkyWest',
  SKX: 'Skyways Express',
  SKY: 'Skymark Airlines',
  SLK: 'SilkAir',
  SLM: 'Surinam Airways',
  SNB: 'Sterling Airlines',
  SNJ: 'Skynet Asia Airways',
  SOL: 'Solomon Airlines',
  SOU: 'Southern Airways',
  SOV: 'Saratov Aviation Division',
  SOZ: 'Sat Airlines',
  SPI: 'South Pacific Island Airways',
  TCF: 'Shuttle America',
  VSV: 'Scat Air',
  TAE: 'TAME',
  TAM: 'TAM Brazilian Airlines',
  TAP: 'TAP Portugal',
  TAR: 'Tunisair',
  TCG: 'Thai Air Cargo',
  TCW: 'Thomas Cook Airlines',
  TCX: 'Thomas Cook Airlines',
  TGN: 'Trigana Air Service',
  TGW: 'Tiger Airways',
  TGG: 'Tigerair Australia',
  THA: 'Thai Airways International',
  THK: 'Turk Hava Kurumu Hava Taksi Isletmesi',
  AIQ: 'Thai AirAsia',
  THY: 'Turkish Airlines',
  TIL: 'Tajikistan International Airlines',
  TJT: 'Twin Jet',
  TLA: 'Translift Airways',
  TMA: 'Trans Mediterranean Airlines',
  TNM: 'Tiara Air',
  TOM: 'Thomsonfly',
  TOS: 'Tropic Air',
  TPA: 'TAMPA',
  TNA: 'TransAsia Airways',
  TRA: 'Transavia Holland',
  TCV: 'TACV',
  ABS: 'Transwest Air',
  TSO: 'Transaero Airlines',
  TUA: 'Turkmenistan Airlines',
  TUI: 'Tuninter',
  TVS: 'Travel Service',
  BLX: 'TUIfly Nordic',
  DTA: 'TAAG Angola Airlines',
  HVK: 'Turkish Air Force',
  LAP: 'TAM Mercosur',
  LOF: 'Trans States Airlines',
  ROT: 'Tarom',
  URN: 'Turan Air',
  TIB: 'TRIP Linhas A',
  GWY: 'USA3000 Airlines',
  UAL: 'United Airlines',
  UAC: 'United Air Charters',
  SVR: 'Ural Airlines',
  UKM: 'UM Airlines',
  USA: 'US Airways',
  USH: 'US Helicopter',
  UTA: 'UTair Aviation',
  AIO: 'United States Air Force',
  UZB: 'Uzbekistan Airways',
  AUI: 'Ukraine International Airlines',
  VLU: 'Valuair',
  VFC: 'Vasco Air',
  HVN: 'Vietnam Airlines',
  MOV: 'VIM Airlines',
  VOI: 'Volaris',
  VDA: 'Volga-Dnepr Airlines',
  VRD: 'Virgin America',
  VEX: 'Virgin Express',
  VGN: 'Virgin Nigeria Airways',
  VIR: 'Virgin Atlantic Airways',
  VVM: 'Viva Macau',
  VLE: 'Volare Airlines',
  VLG: 'Vueling Airlines',
  VLK: 'Vladivostok Air',
  VLO: 'Varig Log',
  VOZ: 'Virgin Australia',
  VRN: 'VRG Linhas Aereas',
  VSP: 'VASP',
  VLM: 'VLM Airlines',
  WEB: 'WebJet Linhas A',
  WLC: 'Welcome Air',
  WJA: 'WestJet',
  WAL: 'Western Airlines',
  WIF: 'Wider\u00f8e',
  JET: 'Wind Jet',
  WON: 'Wings Air',
  WZZ: 'Wizz Air',
  WVL: 'Wizz Air Hungary',
  WOA: 'World Airways',
  SEU: 'XL Airways France',
  CXA: 'Xiamen Airlines',
  LLM: 'Yamal Airlines',
  IYE: 'Yemenia',
  UMK: 'Yuzhmashavia',
  TAN: 'Zanair',
  OOM: 'Zoom Airlines',
  ABL: 'Air Busan',
  SXR: 'Sky Express',
  GLP: 'Globus',
  KZK: 'Air Kazakhstan',
  JAS: 'Japan Air System',
  UBD: 'United Airways',
  FFV: 'Fly540',
  TVF: 'Transavia France',
  MKU: 'Island Air (WP)',
  UIA: 'Uni Air',
  RWZ: 'Red Wings',
  FXX: 'Felix Airways',
  KOQ: 'Kostromskie avialinii',
  GFY: 'Greenfly',
  ELK: 'ELK Airways',
  GBK: 'Gabon Airlines',
  MCA: 'MCA Airlines',
  MAV: 'Maldivo Airlines',
  VNP: 'Virgin Pacific',
  ESR: 'Eastar Jet',
  JNA: 'Jin Air',
  KW1: 'Wataniya Airways',
  BA1: 'Baltic Air lines',
  YCC: 'Ciel Canadien',
  YCP: 'Canadian National Airways',
  '4AA': 'Epic Holiday',
  AXC: 'Indochina Airlines',
  FLB: 'German Air Force - FLB',
  LBL: 'Line Blue',
  LLC: 'FlyLAL Charters',
  TXW: 'Texas Wings',
  DSY: 'Dennis Sky',
  A1F: 'Atifly',
  SZB: 'Aerolineas heredas santa maria',
  JRB: 'Jc royal.britannica',
  CA1: 'CanXpress',
  SHA: 'Sharp Airlines',
  CAP: 'CanXplorer',
  WE1: 'World Experience Airline',
  GCR: 'Tianjin Airlines',
  LOC: 'Locair',
  SQH: 'SeaPort Airlines',
  HCW: 'Star1 Airlines',
  ENJ: 'Enerjet',
  MXI: 'MexicanaLink',
  ISX: 'Island Spirit',
  OBS: 'Orbest',
  SOA: 'Southern Air Charter',
  SVG: 'SVG Air',
  CEY: 'Air Century',
  OLS: 'Sol Lineas Aereas',
  REP: 'Regional Paraguaya',
  NDN: 'Transportes Aereos Cielos Andinos',
  EFY: 'EasyFly',
  ANU: 'Andalus Lineas Aereas',
  DCD: 'Air 26',
  MTW: 'Mauritania Airways',
  CEL: 'CEIBA Intercontinental',
  LMU: 'AlMasria Universal Airlines',
  MSE: 'EgyptAir Express',
  EUD: 'Air Italy Egypt',
  KBR: 'KoralBlue Airlines',
  WRC: 'Wind Rose Aviation',
  GIE: 'Elysian Airlines',
  SEN: 'Sevenair',
  IMP: 'Hellenic Imperial Airways',
  AAN: 'Amsterdam Airlines',
  NAK: 'Arik Niger',
  STP: 'STP Airways',
  SJU: 'Skyjet Airlines',
  TDK: 'Transavia Denmark',
  RFJ: 'Royal Falcon',
  MJX: 'Euroline',
  TRK: 'Turkuaz Airlines',
  VKH: 'Viking Hellas',
  FNA: 'Norlandair',
  FVM: 'Flugfelag Vestmannaeyja',
  GDR: 'Gadair European Airlines',
  MNP: 'Spirit of Manila Airlines',
  CQN: 'Chongqing Airlines',
  GDC: 'Grand China Air',
  CHB: 'West Air China',
  QAX: 'QatXpress',
  '1CH': 'OneChina',
  JOY: 'Joy Air',
  JGN: 'Jagson Airlines',
  QFZ: 'Fars Air Qeshm',
  EAA: 'Eastok Avia',
  JPU: 'Jupiter Airlines',
  VIS: 'Vision Air International',
  KEA: 'Korea Express Air',
  EZA: 'Eznis Airways',
  PFL: 'Pacific Flier',
  PSB: 'Syrian Pearl Airlines',
  IPV: 'Parmiss Airlines (IPV)',
  EUV: 'EuropeSky',
  BZE: 'BRAZIL AIR',
  OME: 'Homer Air',
  '--+': 'U.S. Air',
  PQW: 'PanAm World Airways',
  VWA: 'Virginwings',
  KSY: 'KSY',
  BQB: 'Buquebus L\u00edneas A\u00e9reas',
  KOL: 'SOCHI AIR',
  WAU: 'Wizz Air Ukraine',
  VVN: '88',
  LMM: 'LCM AIRLINES',
  'T&O': "Tom\\\\'s & co airliners",
  AZU: 'Azul',
  LOO: 'LSM Airlines',
  PZY: 'Zapolyarie Airlines',
  FN1: 'Finlandian',
  LIX: 'LionXpress',
  FDB: 'Fly Dubai',
  MDO: 'Domenican Airlines',
  '2CO': 'ConneX European Airline',
  AXZ: 'Aereonautica militare',
  KLS: 'Kal Star Aviation',
  YZZ: 'LSM AIRLINES ',
  ZZZ: 'Zabaykalskii Airlines',
  XBM: 'CBM America',
  '1QA': 'Marysya Airlines',
  WFX: 'Westfalia Express VA',
  BSA: 'Black Stallion Airways',
  GER: 'German International Air Lines',
  TBZ: 'TrasBrasil',
  THS: 'TransBrasil Airlines',
  IIA: 'AIR INDOCHINE',
  HPY: 'Happy Air',
  SRB: 'Solar Air',
  MKG: 'Air Mekong',
  AHO: 'Air Hamburg (AHO)',
  ZTT: 'ZABAIKAL AIRLINES',
  THI: 'TransHolding',
  SZZ: 'SUR Lineas Aereas',
  AA1: 'Aerolineas Africanas',
  SA1: 'Serbian Airlines',
  TYS: 'TransHolding System',
  CCC: 'CCML Airlines',
  ELC: 'Small Planet Airlines',
  FBL: 'Fly Brasil',
  CIF: 'CB Airways UK ( Interliging Flights )',
  '3FF': 'Fly Colombia ( Interliging Flights )',
  TP6: 'Trans Pas Air',
  HYM: 'Himalayan Airlines',
  IG1: 'Indya Airline Group',
  TWD: 'Turkish Wings Domestic',
  ZXY: 'Japan Regio',
  IXO: 'OCEAN AIR CARGO',
  NX1: 'Nihon.jet connect',
  UWW: 'LSM International ',
  BUU: 'Baikotovitchestrian Airlines ',
  LJJ: 'Luchsh Airlines ',
  QQQ: 'ENTERair',
  ZTF: 'Mongolian International Air Lines ',
  TWB: 'Tway Airlines',
  JSR: 'Jusur airways',
  NXB: 'NEXT Brasil',
  WER: 'AeroWorld ',
  ES2: 'Usa Sky Cargo',
  HNX: 'Hankook Airline',
  SAR: 'Sprintair',
  MRS: 'Marusya Airways',
  ERR: 'Era Alaska',
  RRJ: 'AirRussia',
  HA1: 'Hankook Air US',
  SMW: 'Carpatair Flight Training',
  RSY: 'I-Fly',
  WTJ: 'Whitejets',
  VKJ: 'VickJet',
  HAY: 'Hamburg Airways',
  SLC: "Salsa d\\\\'Haiti",
  KND: 'Kan Air',
  CUD: 'Air Cudlua',
  AXE: 'Air Explore',
  N12: '12 North',
  HCC: 'Holidays Czech Airlines',
  COE: 'Comtel Air',
  MIC: 'Mint Airways',
  OBT: 'Orbit Airlines',
  BUR: 'Air Bucharest',
  LAV: 'AlbaStar',
  MAI: 'Mauritania Airlines International',
  MKD: 'MAT Airways',
  AWM: 'Asian Wings Airways',
  RBG: 'Air Arabia Egypt',
  EGS: 'Eagles Airlines',
  YEP: 'YES Airways',
  DSV: 'Direct Aero Services',
  MDP: 'Medallion Air',
  ORC: 'Orchid Airlines',
  AWA: 'Asia Wings',
  GNN: 'Georgian International Airlines',
  BTM: 'Air Batumi',
  NIA: 'Nile Air',
  FDD: 'Feeder Airlines',
  SGG: 'Senegal Airlines',
  CX0: 'Copenhagen Express',
  BCC: 'BusinessAir',
  XOJ: 'XOJET',
  CR7: 'Sky Wing Pacific',
  BEU: 'Bateleur Air',
  AI0: 'Air Indus',
  OAI: 'Orbit International Airlines',
  OAR: 'Orbit Regional Airlines',
  OAN: 'Orbit Atlantic Airways',
  VOO: 'Volotea',
  HTH: 'Helitt L\u00edneas A\u00e9reas',
  RSD: 'Russia State Transport',
  MWI: 'Malaysia Wings',
  ABI: 'Aviabus',
  MJG: 'Michael Airlines',
  KGO: 'Korongo Airlines',
  IDS: 'Indonesia Sky',
  '666': 'Aws express',
  SJS: 'Southjet',
  ZCS: 'Southjet connect',
  XAN: 'Southjet cargo',
  IBS: 'Iberia Express',
  NGB: 'Nordic Global Airlines',
  SCO: 'Scoot',
  ZNA: 'Zenith International Airline',
  OAB: 'Orbit Airlines Azerbaijan',
  FKA: 'Flying kangaroo Airline',
  RSJ: 'RusJet',
  VJC: 'VietJet Air',
  RBY: 'Vision Airlines (V2)',
  WAJ: 'AirAsia Japan',
  YEL: 'Yellowtail',
  RAW: 'Royal Airways',
  FHI: 'FlyHigh Airlines Ireland (FH)',
  XSR: 'Executive AirShare',
  HBH: 'Hebei Airlines',
  KBZ: 'Air KBZ',
  TJA: 'T.J. Air',
  UAT: 'Ukraine Atlantic',
  NMA: 'Nesma Airlines',
  EHN: 'East Horizon',
  MJP: 'Air Majoro',
  RJD: 'Rotana Jet',
  QER: 'SOCHI AIR CHATER',
  MXD: 'Malindo Air',
  HRM: 'Hermes Airlines',
  '\u041a\u0422\u041a': '\u041a\u0430\u0442\u044d\u043a\u0430\u0432\u0438\u0430',
  PKV: '\u041f\u0441\u043a\u043e\u0432\u0430\u0432\u0438\u0430',
  M1F: 'Maryland Air',
  VVC: 'VivaColombia',
  FCM: 'Flybe Finland Oy',
  BGY: 'Bingo Airways',
  BBG: 'Bluebird Airways (BZ)',
  IWA: 'Apache Air',
  JTO: 'Jettor Airlines',
  VQI: 'Flyme (VP)',
  TLM: 'Thai Lion Air',
  GMR: 'Golden Myanmar Airlines',
  CNF: 'Canaryfly',
  KSZ: 'Sunrise Airways',
  NCR: 'National Air Cargo',
  EAV: 'Eastern Atlantic Virtual Airlines',
  TTZ: 'Transair',
  EVC: 'Comfort Express Virtual Charters Albany',
  CEO: 'Comfort Express Virtual Charters',
  FYJ: 'FLYJET',
  SBD: 'Snowbird Airlines',
  KRY: 'Russkie Krylya',
  KHK: 'Kharkiv Airlines',
  XAU: 'XAIR USA',
  RMK: 'Simrik Airlines',
  XPT: 'XPTO',
  DME: 'Royal Flight',
  EGH: 'BBN-Airways',
  TKS: 'Tomsk-Avia',
  NYT: 'Yeti Airlines ',
  '...': 'Avilu',
  KCU: 'Skyline Ulasim Ticaret A.S.',
  ENY: 'Envoy Air',
  CCB: 'CARICOM AIRWAYS (BARBADOS) INC.',
  RAB: 'Rainbow Air (RAI)',
  RAY: 'Rainbow Air Canada',
  RPO: 'Rainbow Air Polynesia',
  RUE: 'Rainbow Air Euro',
  RNY: 'Rainbow Air US',
  TNS: 'Transilvania',
  DOB: 'Dobrolet',
  SAL: 'Spike Airlines',
  GCA: 'Grand Cru Airlines',
  RLX: 'Go2Sky',
  AL1: 'All Argentina',
  AL2: 'All America',
  AL3: 'All Asia',
  '99F': 'All Africa',
  J88: 'Regionalia M\u00e9xico',
  N99: 'All Europe',
  N77: 'All Spain',
  N78: 'Regional Air Iceland',
  K88: 'Voestar',
  '7KK': 'All Colombia',
  '2K2': 'Regionalia Uruguay',
  '9XX': 'Regionalia Venezuela',
  CR1: 'Regionalia Chile',
  '6CC': 'Vuela Cuba',
  '8K8': 'All Australia',
  RWW: 'Fly Europa',
  FPT: 'FlyPortugal',
  MMA: 'Myanmar Airways International',
  VTI: 'Vistara',
  CUH: 'Urumqi Air',
  CBG: 'Guangxi Beibu Gulf Airlines',
  MYU: 'My Indo Airlines',
  FRV: 'Government of Morocco',
  HKC: 'Hong Kong Air Cargo',
  UBG: 'US-Bangla Airlines',
  NJE: 'NetJets Europe',
  BTN: 'Bhutan Airlines',
  IRB: 'Iran Airtour',
  AOJ: 'Avcon Jet',
  IDX: 'Indonesia AirAsia X',
  QQE: 'Qatar Executive',
  CSS: 'SF Airlines',
  RGE: 'Regent Airways',
  CXM: 'AsiaCargo Express',
};
