export const trackedCategories: string[] = [
  'Business',
  'Celebrity',
  'Formula 1',
  'Government',
  'Other',
  'People',
  'Sports',
  'State/Law',
  'Test Aircraft',
  'YouTubers',
];
export const trackedOperators: string[] = [
  '21st Century Fox America',
  'AN124',
  'ARTEMIS Platform',
  'AT&T',
  'AVdef',
  'Aaron Rogers',
  'AbbVie',
  'Abbott Labratories',
  'Accidental Aviator',
  'Adam Scott',
  'Adam Weitsman',
  'Adobe',
  'Aflac',
  'Air Force Materiel Command-GRUMMAN',
  'Air Lease Corp.',
  'Airbus Beluga',
  'Airbus Racer',
  'Aiyawatt Srivaddhanaprabha',
  'Alan Waxman Sixth Street Partners',
  'Albert Avdolyan',
  'Alberto Rodr\u00edguez Baldi (Baldi Hot Springs Hotel)',
  'Alejandro Roemmers',
  'Alex Rodriguez',
  'Aliko Dangote',
  'Alisher Usmanov',
  'Allen & Company',
  'Alyssa Miller',
  'American Express',
  'American Family Insurance',
  'Amgen',
  'Amnon Shashua',
  'Andreessen Horowitz',
  'Andrew Forrest',
  'Andr\u00e9 Esteves',
  'Andy Albright',
  'Angle of Attack',
  'Antonio Gracias (Valor Equity Partners)',
  'Apollo Global Management',
  'Arkady Rotenberg',
  'Arizona Cardinals Football',
  'Army ARES Bombardier Global',
  'Arthur Blank',
  'B-1B',
  'B-29 Superfortress',
  'B-52',
  'BETA Tech eVTOL',
  'BIC Lighters and Pens',
  'BMW Automotive',
  'BNSF Railway',
  'Bahrain Royal Flight',
  'Bank of America',
  'Baron Pilot',
  'Bass Pro Shop',
  'Becki and Chris',
  'Bell V-280 Valor',
  'Beoing E4B',
  'Berkshire Hathaway',
  'Bernie Ecclestone',
  'Berrada Properties',
  'Bill Gates',
  'BlackRock',
  'Blackstone',
  'Blake Shelton',
  'Blaze Grubbs',
  'Blue Max Six',
  'Blue Star Airways',
  'Boeing 737-10 MAX',
  'Boeing 737-7 MAX',
  'Boeing 757 (F-22 Testbed)',
  'Boeing 777 EcoDemonstrator',
  'Boeing 777-9',
  'Boeing 787-8 Test Bed',
  'Boeing C-40A/B Clipper',
  'Boeing Dreamlifter',
  'Boeing E-3G Sentry',
  'Bombardier E-11A',
  'Bombardier Global 7500',
  'Brad Keselowski',
  'Brad Keywell (Groupon and Uptake Tech)',
  'Business',
  'C-9B Skytrain II',
  'CBS Media',
  'CIA Linked',
  'COMCO',
  'COX TV/Communications',
  'CVS',
  'Calspan Defense Corp',
  'Calspan Flight Research',
  'CarMax',
  'Carrier Corp',
  'Carvana/DriveTime',
  'Caterpillar Inc.',
  'Celebrity',
  'Cessna C700',
  'Cessna UC-35A/B',
  'Chairul Tanjung',
  'Chalerm Yoovidhya',
  'Charles Hoskinson',
  'Charles Simonyi',
  'Chase Coleman',
  'Chase Elliot',
  'Chevron',
  'Chick-Fil-A',
  'Chipotle',
  'Choice Hotels',
  'Chris Sacca',
  'Cisco Systems',
  'CitationMax',
  'Citigroup',
  'Clayton Homes',
  'Coca-Cola',
  'Cohen Brothers',
  'Colts',
  'Congra Brands',
  'Conoco',
  'ConocoPhillips',
  'Costar Realty',
  'Costco Wholesale',
  'Cracker Barrel',
  'Craig Leipold/Minnesota Wild',
  'Craig McCaw',
  'Cristiano Ronaldo',
  'Crown Prince Salman bin Hamad bin Isa Al Khalifa',
  'Cummins Inc',
  'DJ Khaled',
  'DLR - German Aerospace Center',
  'DMB Associates Real Estate',
  'DOJ (Dept. of Justice)',
  'DS Advisors (Equitec)',
  'Dale Earnhardt Family',
  'Dallas Cowboys',
  'Dallas Mavericks',
  'Dan Bilzerian',
  'Dan Newlin',
  'Dan Snyder',
  'Danny Jenkins',
  'Dassault Falcon Response Team',
  'Dave Sparks / HeavyD',
  'David Ellison',
  'David Geffen',
  'David Grain',
  'David Katzman (SmileDirect)',
  'David MacNeil',
  'David Rubenstein',
  'David Sacks',
  'David Tepper',
  'DeVos Family',
  'Dell',
  'Dennis Washington',
  'Denny Hamlin Racing',
  'Detroit Red Wings',
  "Dick's Sporting Goods",
  'Dierks Bentley',
  'Dietrich Mateschitz',
  'DigitalBridge',
  'Dillards Dept. Stores',
  'Dippin Dots',
  'Discovery Land Company Real Estate',
  'Disney',
  'Dmitry Balyasny',
  'Dollar General',
  'Dollar Tree',
  "Domino's",
  "Don Av8's",
  'Donald Trump',
  'Dr. Phil & Son',
  'Draft Kings',
  'Drake',
  'Drew Brees',
  'Duke Energy',
  'Dutch Bros Coffee',
  'E-11A BACN & R1 Sentinel',
  'ENTP LIFE',
  'Ed DeBartolo',
  'Edward Norton',
  'Eli Lilly and Company',
  'Elon Musk',
  'Enterprise Car Rental',
  'Eric Lefkofsky (Groupon)',
  'Eric Schmidt',
  'Erik Prince',
  'Eviation Alice',
  'Excalibur Testbed',
  'ExxonMobile',
  'Eytan Stibbe',
  'FAA',
  'FAAM Airborne Laboratory',
  'FBI (Federal Bureau of Investigation)',
  'FEST (Foreign Emergency Support Team)',
  'Falcon 6X',
  'FedEx',
  'Fernando Alonso',
  'Fertitta (Casinos + Houston Rockets)',
  'First Horizon Bank',
  'Five Guys',
  'Flavio Briatore',
  'Floyd Mayweather',
  'Fly With Own (Non-owner Pilot)',
  'Ford',
  "Formula 1 VIP's",
  'France Presidency (COTAM)',
  'Franklin Templeton Investments',
  'Fred Luddy',
  'GAP Inc.',
  'Garth Brooks',
  'Gear Down',
  'Gene Haas',
  'General Dynamics',
  'Germany Chancellery (Flugbereitschaft)',
  'George Lucas',
  'George Strait',
  'George William Davies',
  'Ginger the Plane',
  'Glennon Crowell Jr.',
  'Globus Medical',
  'Goldman Sachs',
  'Goodyear Tire & Rubber Company',
  'Google',
  'Government',
  'Government 707',
  'Government State of Kuwait',
  'Government of Abu Dhabi',
  'Government of Algeria',
  'Government of Angola',
  'Government of Argentina',
  'Government of Armenia',
  'Government of Azerbaijan',
  'Government of Bangladesh',
  'Government of Belarus',
  'Government of Belgium',
  'Government of Bolivia',
  'Government of Brazil',
  'Government of Bulgaria',
  'Government of Canada',
  'Government of Chile',
  "Government of Cote d'Ivoire",
  'Government of Croatia',
  'Government of Czech Republic',
  'Government of Ecuador',
  'Government of Egypt',
  'Government of Equatorial Guinea',
  'Government of France',
  'Government of Gabon',
  'Government of Germany',
  'Government of Hungary',
  'Government of India',
  'Government of Iran',
  'Government of Ireland',
  'Government of Italy',
  'Government of Japan',
  'Government of Jordan',
  'Government of Malaysia',
  'Government of Nigeria',
  'Government of North Korea',
  'Government of Pakistan',
  'Government of Panama',
  'Government of Poland',
  'Government of Qatar',
  'Government of Russia',
  'Government of Saudi Arabia',
  'Government of Slovenia',
  'Government of South Africa',
  'Government of Spain',
  'Government of Switzerland',
  'Government of Tanzania',
  'Government of Thailand',
  'Government of Turkey',
  'Government of Turkmenistan',
  'Government of Ukraine',
  'Government of Zambia',
  'Government of the Netherlands',
  'Government of the United Kingdom',
  'Government/Police of Mexico',
  'Grady White Boats',
  'Grant Baker',
  'Grant Cardone',
  'Great Clips',
  'Greg Wyler (OneWeb)',
  'Guggenheim Partners',
  'Gulfstream C-20C',
  'Gulfstream C-20H',
  'Gulfstream C-37A',
  'Gulfstream C-37B',
  'Gulfstream G400',
  'Gulfstream G700',
  'Gulfstream G800',
  'Gwyenn Shotwell (SpaceX)',
  'HP',
  'Ha Du Long',
  'Haim Saban',
  'Hallmark Cards',
  'Hard Rock',
  'Harrison Ford',
  'Hendrick Motorsports',
  'Hermeus Quarterhorse',
  'Hershey Foods',
  'Hess Corp',
  'Hilton Hotels',
  'Hobby Lobby',
  'Honeywell',
  'Honeywell 757 Test Bed',
  'Houston Rockets',
  'Huntsman Jet',
  'Hy-Vee Grocery',
  'Hyundai',
  'IAI C-38A Courier',
  'IBM',
  'Innovation First Research and Development Inc',
  'Intel Air Shuttle (Intel)',
  'International Air Response',
  'Israel Air Force',
  'J Balvin',
  'JCB Manufacturing',
  'JDS Development',
  'JP Morgan',
  'JR Garage (JR Aviation)',
  'JR Motorsports',
  'JRK Property Holdings',
  'Jack Ma',
  'Jackie Chan',
  'Jacksons Food Stores',
  'Jacob Arabo',
  'James Dyson',
  'James Simmons',
  'James Williamson',
  'Jan Koum',
  'Japan Prime Minister',
  'Jared Isaacman',
  'Jared Kushner',
  'Jason Kelce',
  'Jay Penske',
  'Jay-Z',
  'Jeff Bezos',
  'Jeff Swickard',
  'Jeffrey Soffer',
  'Jeffrey Vinik',
  'Jerry Jones',
  'Jerry Savelle (televangelist )',
  'Jerry Seinfeld',
  'Jerry Yang',
  'Jim Breyer',
  'Jim Carrey',
  'Jim Crane',
  'Jim Crane/Houston Astros',
  'Jim Ovia',
  'Jimmy Buffet',
  'Jimmy John Liautaud',
  'Jimmy Johnson',
  'Joby Aviation eVTOL',
  'Jody Allen/Seahawks & Trail Blazers (Paul Allen Estate)',
  'Joe Gibbs Racing',
  'Joe Manchin',
  'Joe Tsai',
  'John A. Sobrato',
  'John Deere',
  'John Doerr',
  'John Elway',
  'John Henry/Boston Red Sox',
  'John Malone',
  'John Mara/NY Giants',
  'John McCaw',
  'John Middleton/Phillies',
  'John Paulson',
  'John Ruiz',
  'John Schnatter (Papa Johns)',
  'John Staluppi',
  'John Travolta',
  'John W. Henry',
  'Johnny Ive',
  'Johnson & Johnson',
  'Johnson Development',
  'Johnsonville Brats',
  'Johor Royal Family',
  'Jon A Shirley',
  'Jon Gray',
  'Joseph Edelman',
  'Josh Altman',
  'Julio Iglesias',
  'Justin Bieber',
  'Keith Urban',
  'Ken Griffin',
  'Kenny Chesney',
  'Kevin Harvey',
  'Khosla Ventures',
  'Kid Rock',
  'Kiewit Engineering Co.',
  'Kilmer Management LP',
  'Kim Kardashian',
  'Kimbal Musk',
  'Kingdom of Eswatini',
  'Knight-Swift Trucking',
  'Koch Industries',
  'Kohler Co.',
  'Kris Krohn',
  'Kroger',
  'Kylie Jenner',
  'L-3 Communications',
  'L3 Harris Technologies',
  'LA Chargers',
  'LG Electronics',
  'Lance Stroll',
  'Larry Ellison',
  'Larry Page',
  'Las Vegas Golden Knights',
  'Las Vegas Sands',
  'Laurence Escalante (theleecollection)',
  'Laurene Powell Jobs',
  'Lawrence Stroll',
  'Learjet C-21A',
  'Leisure Pools',
  'Leon Black',
  'Leonardo AW609',
  'Liberty Mutual Insurance',
  'Life Lion (Hershey Medical Center)',
  'LifeFlightNetwork',
  'Lionel Messi',
  'Lockheed Gulfstream',
  'Lockheed Martin',
  'Louis Bacon',
  'Lowes',
  'Luke Bryan',
  'Lyden Air Cargo',
  'MATCH1N',
  'MIT Lincoln Lab',
  'MQ-20 Avenger',
  'Maersk Shipping Company',
  'Magic Johnson',
  'Mandalay Vegas Resorts',
  'Marco Andretti',
  'Mark Benioff',
  'Mark Burnett',
  'Mark Cuban',
  'Mark Juncosa (SpaceX VP)',
  'Mark Wahlberg',
  'Mark Zuckerberg',
  'Marriott Hotels',
  'Mary Kay Inc.',
  'Matt Guthmiller',
  'Max Verstappen',
  'Mayo Clinic',
  'McDonalds',
  'McNeil Consumer Healthcare (Tylenol)',
  'Meet Kevin',
  'Meet Kevin (YouTuber)',
  'Meijer Stores',
  'Melinda Gates',
  'Menards',
  'Merck',
  'Michael Jordan',
  'Michael Milken',
  'Michael Niederst (Real estate)',
  'Michael Saylor (MicroStrategy)',
  'Michael Schumacher',
  'Micke Lang',
  'Micron',
  'Mike Bloomberg',
  'Mike Lindell',
  'Mike Patey',
  'Miliken',
  'Military HALO Gulfstreams',
  'Mohamed El Enein',
  'MojoGrip',
  'Morgan Stanley',
  'Morgan and Morgan Law Firm',
  'Murdoch Family',
  'NASA',
  'NAV Canada Flight Inspection',
  'Nancy Walton',
  'Nanoworks',
  'National Nuclear Security Administration',
  'National Science Foundation',
  'Nelson Peltz',
  'Nelson Piquet',
  'Nestle USA',
  'Netflix',
  'New Zealand Air Force',
  'Niagara Water Bottling',
  'Nick Marietta',
  'Nick Woodman',
  'Nike',
  'Norfolk Southern Railroad',
  'Northrup Grumman',
  'Oaktree Capital',
  'Oleg Deripaska',
  'Olympia Aviation (Detroit Red Wings/Tigers)',
  'Oprah Winfrey',
  'Oracle',
  'Orbis Flying Eye Hospital',
  'Other',
  'OtterBox',
  'Ozuna',
  'PACCAR',
  'Palantir',
  'Panda Express',
  'Pap\u00e9 Machinery',
  'Paramount Pictures',
  'Paris Hilton',
  'Pasaca Capital',
  'Patek Philippe SA',
  'Patrick Dovigi',
  'Patrick Mahomes (Part Owner)',
  'Patriots',
  'Paul L. Foster',
  'Paul Randy',
  'Paul Tudor Jones',
  'PayPal',
  'Penn National Gaming',
  'Penske Racing',
  'People',
  'Pepsi',
  'Perenco',
  'Peter Lim',
  'Peter Thiel',
  'Peterson Companies',
  'Pfizer',
  'Phil Knight (NIKE)',
  'Phil Ruffin',
  'Philadelphia Eagles',
  'Phillip Sarofim',
  'Phoenix Air Gulfstream II',
  'Pickle Driver (SF50)',
  'Piero Ferrari',
  'Pierre Omidyar',
  'Pitbull',
  'Plane and Dirt Simple',
  'Playboy',
  'Plumb Bill Pay',
  'Prada',
  'Pratt & Whitney Canada 747SP',
  'Precision Castparts',
  'Premier1Driver',
  'Prime Inc.',
  'Principal Financial',
  'Pritzker Family',
  'Proctor & Gamble',
  'Prudential Insurance',
  'Publix Supermarkets',
  'Puma',
  'Purina Petcare',
  'Qualcomm',
  'Quest Diagnostics (BE58)',
  'Quest Diagnostics (Other)',
  'Quest Diagnostics (PC12)',
  'RC-12X Guardrail',
  'RQ-4 Global Hawk',
  'RTW Investments',
  'Ralph Lauren',
  'Raytheon',
  'RealPage Real Estate',
  'Related Companies (Stephen Ross)',
  'Remon Voss',
  'Republic of Tatarstan(RU)',
  'Resturant Brands Intl.',
  'Richard Branson',
  'Richard Childress Racing',
  'Richard T. Santulli',
  'Rick Caruso',
  'Rick Ross',
  'Ricky Gutierrez & JR Garage',
  'Rihanna',
  'Riley Herbst',
  'Robert F. Smith',
  'Robert Herjavec',
  'Robert Kraft',
  'Robert Penske',
  'Robert Pera',
  'Rocket Lab Helicopters',
  'Roleof Botha',
  'Rolls Royce Test Bed',
  'Roman Abramovich',
  'Ron DeSantis',
  'Ron Fowler/San Diego Padres',
  'Ronald Perelman',
  'Rooms to Go',
  'Rory McIlroy',
  'Royal Air Force',
  'Royal Australian Air Force',
  'Rubens Barrichello',
  'Russell Wilson',
  'RyanAir Support Aircraft',
  'S C Johnson',
  'Saints/Pelicans',
  "Samaritan's Purse",
  'Sammy Hagar',
  'Samsung',
  'Santo Domingo Family',
  'Saudi Royal Flight',
  'Sawiris Family',
  'Scaled Composites Proteus',
  'ScottsMiracle-Gro',
  'Scuderia AlphaTauri',
  'Sebastian Kulczyk',
  'Sebastian Maniscalco',
  'Sergey Brin',
  'Sergio Garcia',
  'Sergio Perez',
  'Shahid Khan',
  'Shaq',
  'Shell Oil',
  'Sierra Pacific Industries',
  'Sikorsky SB-1 Defiant',
  'Silver Lake Technology Management',
  'Simon Property Group (Malls)',
  'SlowAsianDriver',
  'Snapchat/Evan Spiegel',
  'South Park Media',
  'SpaceX',
  'Sports',
  'Stan Kronke',
  'Standard Industries',
  'Stanley Druckenmiller',
  'State Govt./Law',
  'State of Alabama',
  'State of Alaska',
  'State of Arizona',
  'State of Arkansas',
  'State of California',
  'State of Colorado',
  'State of Connecticut',
  'State of Delaware',
  'State of Florida',
  'State of Georgia',
  'State of Idaho',
  'State of Illinois',
  'State of Indiana',
  'State of Iowa',
  'State of Kansas',
  'State of Kentucky',
  'State of Louisiana',
  'State of Maine',
  'State of Maryland',
  'State of Massachusetts',
  'State of Michigan',
  'State of Minnesota',
  'State of Mississippi',
  'State of Missouri',
  'State of Montana',
  'State of Nebraska',
  'State of Nevada',
  'State of New Hampshire',
  'State of New Jersey',
  'State of New Mexico',
  'State of New York',
  'State of North Carolina',
  'State of North Dakota',
  'State of Ohio',
  'State of Oklahoma',
  'State of Oregon',
  'State of Pennsylvania',
  'State of South Carolina',
  'State of South Dakota',
  'State of Tennessee',
  'State of Texas',
  'State of Utah',
  'State of Virginia',
  'State of Washington',
  'State of West Virginia',
  'State of Wisconsin',
  'State of Wyoming',
  'Stefan Drury',
  'Stephanie Shojaee (Shoma Real Estate)',
  'Stephen Schwarzman',
  'Steve Ballmer',
  'Steve Witkoff',
  'Steve Wynn/Wynn Resorts',
  'Steven Rattner',
  'Steven Spielberg',
  'Stevie Triesenberg',
  'Stewart-Haas Racing',
  'Stratos 716',
  'Surveillance Australia',
  'Swiss Air Ambulance',
  'T2 Aviation (Oil Spill Response',
  'Taylor Gerring',
  'Taylor Swift',
  'Ted Leonsis',
  'Ted Turner',
  'Ted Waitt',
  'Tenax Aerospace',
  'Tennessee Titans',
  'Test Aircraft',
  'Textron AirLand Scorpion',
  'Textron/Beechcraft Denali',
  'Thomas Siebel',
  'Tiger Woods',
  'Tilman Fertitta',
  'Tim Gillean',
  'Toby Kieth',
  'Tom Cruise',
  'Tom Gores',
  'Tom Werner',
  'Tom and Steuart Walton',
  'Tommy Hilfiger',
  'Tony Robbins',
  'Tony Stewart',
  "Top Aces F16's",
  'Trent Palmer',
  'Travis Scott',
  'Trevor Milton',
  'Troy Aikman',
  'Ty Warner',
  'Tyler Perry',
  'UK Royal Family (RAF)',
  'U.S. Govt. Special Missions',
  'U.S. Marines C-40A',
  'U.S. Marshals (JPATS/Prisoner Transport)',
  'USAF/Big Safari/SierraNevCor',
  'USCG (Coast Guard)',
  'USDHS (Dept. Homeland Sec.)',
  'Ukraine War Survalliance Plane',
  'United States of America 747/757',
  'Vasil Bojkov',
  'Vick Tipnes',
  'Victory Aviation (NASCAR)',
  'WC-135R Constant Phoenix',
  'WWE',
  'Wes Edens',
  'Wesley Edens',
  'Wifi-Money',
  'Winklevoss Twins (Crypto)',
  'Woody Johnson',
  'YouTubers',
  'Yusaku Mazawa',
  'Zero G Plane',
  'christophe jouany',
  'steveo1kinevo',
];
